spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true


spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-54-160-109-68.compute-1.amazonaws.com/d5p5st0kvud48a
  username: gjvprdmdaifubr
  password: e45fc606e9b8c385da82955ce380d2188e952ac545e947ae0d7529abe478636e
  platform: postgres
  driver-class-name: org.postgresql.Driver


jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  #30 days
  token.expired-time-ms: 2592000000

spring:
  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SMA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="hbwlmtzu" password="C0hClPR-7mL73JibldMzf5rqG22ZVtAo";
    consumer:
      properties.spring.json.trusted.packages: "*"
      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
      group-id: alarm
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-node: MANUAL
    producer:
      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.enable.idempotence: false
    topic:
      alarm: hbwlmtzu-alarm